spring:
  r2dbc:
    url: r2dbc:mysql://${DB_CONNECT}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool:
      enabled: true
      initial-size: 10
      max-size: 15
      max-idle-time: 10m
      validation-depth: remote