name: CI Finance Fit

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build and generate coverage report
        run: ./gradlew build

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Especifique a versão do Python que deseja usar

      - name: Install dependencies
        run: pip install beautifulsoup4

      - name: Check coverage percentage
        run: python3 ./scripts/check_coverage.py ./build/reports/jacoco/test/html/index.html
